//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "access_grants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub object_json: String,
    #[sea_orm(column_type = "Text")]
    pub grantee_json: String,
    #[sea_orm(column_type = "Text")]
    pub purpose_json: String,
    #[sea_orm(column_type = "Text")]
    pub disclosure: String,
    #[sea_orm(column_type = "Text")]
    pub calculation_access: String,
    #[sea_orm(column_type = "Text")]
    pub effective_from: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_to: Option<String>,
    pub granted_by: i64,
    #[sea_orm(column_type = "Text")]
    pub granted_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revoked_on: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub note: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::people::Entity",
        from = "Column::GrantedBy",
        to = "super::people::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    People,
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::People.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
