//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "access_policies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub object_json: String,
    #[sea_orm(column_type = "Text")]
    pub calculation_access: String,
    #[sea_orm(column_type = "Text")]
    pub restricted_disclosure: String,
    #[sea_orm(column_type = "Text")]
    pub effective_from: String,
    pub version: i64,
    pub changed_by: i64,
    #[sea_orm(column_type = "Text")]
    pub changed_at: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::people::Entity",
        from = "Column::ChangedBy",
        to = "super::people::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    People,
    #[sea_orm(has_many = "super::policy_full_access::Entity")]
    PolicyFullAccess,
    #[sea_orm(has_many = "super::policy_purposes::Entity")]
    PolicyPurposes,
}

impl Related<super::policy_full_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PolicyFullAccess.def()
    }
}

impl Related<super::policy_purposes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PolicyPurposes.def()
    }
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        super::policy_full_access::Relation::People.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::policy_full_access::Relation::AccessPolicies
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
