//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub institution: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub holder_kind: String,
    pub holder_company_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub liquidity_json: String,
    pub minimum_balance_minor: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub minimum_balance_currency: Option<String>,
    pub transfer_delay_days: i64,
    #[sea_orm(column_type = "Text")]
    pub tax_treatment: String,
    #[sea_orm(column_type = "Text")]
    pub source_of_truth: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_reconciled: Option<String>,
    pub withdrawals_permitted: i64,
    pub include_in_household: i64,
    pub settled_balance_minor: i64,
    pub pending_balance_minor: i64,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_fees::Entity")]
    AccountFees,
    #[sea_orm(has_many = "super::account_fund_categories::Entity")]
    AccountFundCategories,
    #[sea_orm(has_many = "super::account_owners::Entity")]
    AccountOwners,
    #[sea_orm(has_many = "super::actual_transactions::Entity")]
    ActualTransactions,
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::HolderCompanyId",
        to = "super::companies::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Companies,
    #[sea_orm(has_many = "super::reservations::Entity")]
    Reservations,
}

impl Related<super::account_fees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountFees.def()
    }
}

impl Related<super::account_fund_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountFundCategories.def()
    }
}

impl Related<super::account_owners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountOwners.def()
    }
}

impl Related<super::actual_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActualTransactions.def()
    }
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reservations.def()
    }
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        super::account_owners::Relation::People.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::account_owners::Relation::Accounts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
