//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assumptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub certainty: String,
    #[sea_orm(column_type = "Text")]
    pub source_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub accepted_on: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expires_on: Option<String>,
    pub private_to: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assumption_series::Entity")]
    AssumptionSeries,
    #[sea_orm(
        belongs_to = "super::people::Entity",
        from = "Column::PrivateTo",
        to = "super::people::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    People,
}

impl Related<super::assumption_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssumptionSeries.def()
    }
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::People.def()
    }
}

impl Related<super::event_series::Entity> for Entity {
    fn to() -> RelationDef {
        super::assumption_series::Relation::EventSeries.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assumption_series::Relation::Assumptions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
