//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "companies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub jurisdiction: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
    #[sea_orm(has_many = "super::company_constraints::Entity")]
    CompanyConstraints,
    #[sea_orm(has_many = "super::company_employees::Entity")]
    CompanyEmployees,
    #[sea_orm(has_many = "super::company_owners::Entity")]
    CompanyOwners,
    #[sea_orm(has_many = "super::company_roles::Entity")]
    CompanyRoles,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::company_constraints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyConstraints.def()
    }
}

impl Related<super::company_employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyEmployees.def()
    }
}

impl Related<super::company_owners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyOwners.def()
    }
}

impl Related<super::company_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
