//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub direction_json: String,
    pub expected_minor: i64,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub recurrence_json: String,
    pub settlement_lag_days: i64,
    pub availability_lag_days: i64,
    pub intraday_order: i64,
    pub account_id: i64,
    pub linked_account_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub entity_json: String,
    #[sea_orm(column_type = "Text")]
    pub certainty: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub tax_treatment: String,
    pub scenario_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::LinkedAccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Accounts1,
    #[sea_orm(has_many = "super::assumption_series::Entity")]
    AssumptionSeries,
    #[sea_orm(has_many = "super::historical_payments::Entity")]
    HistoricalPayments,
    #[sea_orm(has_many = "super::reconciliation_links::Entity")]
    ReconciliationLinks,
    #[sea_orm(has_many = "super::series_amount_changes::Entity")]
    SeriesAmountChanges,
    #[sea_orm(has_many = "super::series_exceptions::Entity")]
    SeriesExceptions,
}

impl Related<super::assumption_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssumptionSeries.def()
    }
}

impl Related<super::historical_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HistoricalPayments.def()
    }
}

impl Related<super::reconciliation_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReconciliationLinks.def()
    }
}

impl Related<super::series_amount_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesAmountChanges.def()
    }
}

impl Related<super::series_exceptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesExceptions.def()
    }
}

impl Related<super::assumptions::Entity> for Entity {
    fn to() -> RelationDef {
        super::assumption_series::Relation::Assumptions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assumption_series::Relation::EventSeries.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
