//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "households")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub singleton: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub household_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub base_currency: String,
    #[sea_orm(column_type = "Text")]
    pub as_of: String,
    #[sea_orm(column_type = "Text")]
    pub rule_tie_break: String,
    pub last_saved_at: i64,
    #[sea_orm(column_type = "Text")]
    pub last_written_by_version: String,
    #[sea_orm(column_type = "Text")]
    pub format_lineage: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
