//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "people")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_grants::Entity")]
    AccessGrants,
    #[sea_orm(has_many = "super::access_policies::Entity")]
    AccessPolicies,
    #[sea_orm(has_many = "super::account_owners::Entity")]
    AccountOwners,
    #[sea_orm(has_many = "super::assumptions::Entity")]
    Assumptions,
    #[sea_orm(has_many = "super::audit_events::Entity")]
    AuditEvents,
    #[sea_orm(has_many = "super::company_employees::Entity")]
    CompanyEmployees,
    #[sea_orm(has_many = "super::company_owners::Entity")]
    CompanyOwners,
    #[sea_orm(has_many = "super::company_roles::Entity")]
    CompanyRoles,
    #[sea_orm(has_many = "super::goals::Entity")]
    Goals,
    #[sea_orm(has_many = "super::policy_full_access::Entity")]
    PolicyFullAccess,
    #[sea_orm(has_many = "super::scenarios::Entity")]
    Scenarios,
}

impl Related<super::access_grants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessGrants.def()
    }
}

impl Related<super::account_owners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountOwners.def()
    }
}

impl Related<super::assumptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assumptions.def()
    }
}

impl Related<super::audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditEvents.def()
    }
}

impl Related<super::company_employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyEmployees.def()
    }
}

impl Related<super::company_owners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyOwners.def()
    }
}

impl Related<super::company_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyRoles.def()
    }
}

impl Related<super::goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Goals.def()
    }
}

impl Related<super::policy_full_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PolicyFullAccess.def()
    }
}

impl Related<super::scenarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scenarios.def()
    }
}

impl Related<super::access_policies::Entity> for Entity {
    fn to() -> RelationDef {
        super::policy_full_access::Relation::AccessPolicies.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::policy_full_access::Relation::People.def().rev())
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::account_owners::Relation::Accounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::account_owners::Relation::People.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
