//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "policy_purposes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub purpose: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_policies::Entity",
        from = "Column::PolicyId",
        to = "super::access_policies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccessPolicies,
}

impl Related<super::access_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
