//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "policy_full_access")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    pub person_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_policies::Entity",
        from = "Column::PolicyId",
        to = "super::access_policies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccessPolicies,
    #[sea_orm(
        belongs_to = "super::people::Entity",
        from = "Column::PersonId",
        to = "super::people::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    People,
}

impl Related<super::access_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessPolicies.def()
    }
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::People.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
