//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reservations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub account_id: i64,
    pub amount_minor: i64,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub coverage_json: String,
    pub nested_in_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub hardness: String,
    #[sea_orm(column_type = "Text")]
    pub purpose: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub released_on: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::NestedInId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SelfRef,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
