//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rule_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub rule_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub changed_on: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rules::Entity",
        from = "Column::RuleId",
        to = "super::rules::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Rules,
}

impl Related<super::rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
