//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub scope_json: String,
    #[sea_orm(column_type = "Text")]
    pub trigger_json: String,
    #[sea_orm(column_type = "Text")]
    pub action_json: String,
    pub priority: i64,
    #[sea_orm(column_type = "Text")]
    pub effective_from: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_to: Option<String>,
    pub enabled: i64,
    pub scenario_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub explanation: String,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rule_conditions::Entity")]
    RuleConditions,
    #[sea_orm(has_many = "super::rule_versions::Entity")]
    RuleVersions,
    #[sea_orm(
        belongs_to = "super::scenarios::Entity",
        from = "Column::ScenarioId",
        to = "super::scenarios::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Scenarios,
}

impl Related<super::rule_conditions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuleConditions.def()
    }
}

impl Related<super::rule_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuleVersions.def()
    }
}

impl Related<super::scenarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scenarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
