//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "scenario_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub scenario_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub value_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::scenarios::Entity",
        from = "Column::ScenarioId",
        to = "super::scenarios::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Scenarios,
}

impl Related<super::scenarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scenarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
