//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "scenario_components")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub scenario_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    pub component_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::scenarios::Entity",
        from = "Column::ComponentId",
        to = "super::scenarios::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Scenarios2,
    #[sea_orm(
        belongs_to = "super::scenarios::Entity",
        from = "Column::ScenarioId",
        to = "super::scenarios::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Scenarios1,
}

impl ActiveModelBehavior for ActiveModel {}
