//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "series_exceptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub series_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub original_due: String,
    #[sea_orm(column_type = "Text")]
    pub kind_json: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_series::Entity",
        from = "Column::SeriesId",
        to = "super::event_series::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventSeries,
}

impl Related<super::event_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSeries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
