//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tax_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub pack_id: i64,
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub tax_type: String,
    #[sea_orm(column_type = "Text")]
    pub scope: String,
    #[sea_orm(column_type = "Text")]
    pub kind_json: String,
    #[sea_orm(column_type = "Text")]
    pub timing_json: String,
    #[sea_orm(column_type = "Text")]
    pub effective_from: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_to: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub explanation: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tax_packs::Entity",
        from = "Column::PackId",
        to = "super::tax_packs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TaxPacks,
    #[sea_orm(has_many = "super::tax_rule_categories::Entity")]
    TaxRuleCategories,
}

impl Related<super::tax_packs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxPacks.def()
    }
}

impl Related<super::tax_rule_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxRuleCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
