//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tax_rule_categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tax_rule_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i64,
    #[sea_orm(column_type = "Text")]
    pub category: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tax_rules::Entity",
        from = "Column::TaxRuleId",
        to = "super::tax_rules::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TaxRules,
}

impl Related<super::tax_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxRules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
